#ifndef SCLAB_VERSION_H
#define SCLAB_VERSION_H

#define SCLAB_VERSION_MAJOR 1
#define SCLAB_VERSION_MINOR 0
#define SCLAB_VERSION_PATCH 0
#define SCLAB_VERSION_TWEAK 
#define SCLAB_VERSION "1.0.0"

#endif  // SCLAB_VERSION_H
